# permissions for end users to view demoones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoone-viewer-role
rules:
- apiGroups:
  - demos.sdbrett.com
  resources:
  - demoones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demos.sdbrett.com
  resources:
  - demoones/status
  verbs:
  - get
