# permissions for end users to edit demoones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoone-editor-role
rules:
- apiGroups:
  - demos.sdbrett.com
  resources:
  - demoones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demos.sdbrett.com
  resources:
  - demoones/status
  verbs:
  - get
