apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-one
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      namespace: demo-one
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /usr/share/nginx/html/index.html
            name: html
            subPath: index.html
      volumes:
        - name: html
          configMap:
            name: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: demo-one
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

